// sentences.js
const sentences = [
  { infinitive: "eat", participle: "eaten", complement: "spicy food" },
  { infinitive: "break", participle: "broken", complement: "a bone" },
  { infinitive: "travel", participle: "travelled", complement: "to another continent" },
  { infinitive: "see", participle: "seen", complement: "a famous monument" },
  { infinitive: "ride", participle: "ridden", complement: "a horse" },
  { infinitive: "sing", participle: "sung", complement: "in public" },
  { infinitive: "write", participle: "written", complement: "a poem" },
  { infinitive: "swim", participle: "swum", complement: "in the ocean" },
  { infinitive: "forget", participle: "forgotten", complement: "someone's birthday" },
  { infinitive: "lose", participle: "lost", complement: "my keys" },
  { infinitive: "win", participle: "won", complement: "a competition" },
  { infinitive: "fall", participle: "fallen", complement: "off a bicycle" },
  { infinitive: "meet", participle: "met", complement: "a celebrity" },
  { infinitive: "fly", participle: "flown", complement: "in a plane" },
  { infinitive: "drive", participle: "driven", complement: "a car" },
  { infinitive: "drink", participle: "drunk", complement: "coffee" },
  { infinitive: "read", participle: "read", complement: "a book in English" },
  { infinitive: "give", participle: "given", complement: "a speech" },
  { infinitive: "tell", participle: "told", complement: "a lie" },
  { infinitive: "make", participle: "made", complement: "a cake from scratch" },
    { infinitive: "forget", participle: "forgotten", complement: "my homework at home" },
  { infinitive: "sleep", participle: "slept", complement: "in class" },
  { infinitive: "laugh", participle: "laughed", complement: "at the wrong moment" },
  { infinitive: "send", participle: "sent", complement: "a message to the wrong person" },
  { infinitive: "wear", participle: "worn", complement: "my clothes inside out" },
  { infinitive: "drop", participle: "dropped", complement: "my phone on the floor" },
  { infinitive: "lose", participle: "lost", complement: "something important" },
  { infinitive: "say", participle: "said", complement: "something embarrassing" },
  { infinitive: "trip", participle: "tripped", complement: "in front of other people" },
  { infinitive: "break", participle: "broken", complement: "something by accident" },

  { infinitive: "eat", participle: "eaten", complement: "too much chocolate" },
  { infinitive: "drink", participle: "drunk", complement: "milk straight from the bottle" },
  { infinitive: "hide", participle: "hidden", complement: "something from my parents" },
  { infinitive: "copy", participle: "copied", complement: "someone else's homework" },
  { infinitive: "forget", participle: "forgotten", complement: "where I put my phone" },

  { infinitive: "watch", participle: "watched", complement: "the same movie more than three times" },
  { infinitive: "cry", participle: "cried", complement: "because of a movie" },
  { infinitive: "sing", participle: "sung", complement: "in the shower" },
  { infinitive: "dance", participle: "danced", complement: "when nobody was watching" },
  { infinitive: "talk", participle: "talked", complement: "to myself" },

  { infinitive: "pretend", participle: "pretended", complement: "to understand when I didn’t" },
  { infinitive: "be", participle: "been", complement: "afraid of the dark" },
  { infinitive: "wake", participle: "woken", complement: "up too late for school" },
  { infinitive: "forget", participle: "forgotten", complement: "someone’s name immediately" },
  { infinitive: "laugh", participle: "laughed", complement: "so much that I couldn’t stop" }
];
